name: inf
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.22.3
  - torchvision=0.9.2
  - cudatoolkit=10.2
  - pytorch=1.8.2
  - cython
  - matplotlib
  - scikit-learn
  - wandb
  - ninja
